### ISSUE TITLE
Class 'Ctct\ConstantContact' not found

### ISSUE THREAD

**Issue by bobartlett** [shankx50/constant-contact-subscribe#6]
I am receiving the following error when submitting my form. Any thoughts on what might be causing it?

`Class 'Ctct\ConstantContact' not found (/srv/app/htdocs/craft/plugins/constantcontactsubscribe/controllers/ConstantContactSubscribe_ListController.php:34)

#0 /srv/app/htdocs/craft/app/framework/web/actions/CInlineAction.php(49): Craft\ConstantContactSubscribe_ListController->actionSubscribe()
#1 /srv/app/htdocs/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#2 /srv/app/htdocs/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#3 /srv/app/htdocs/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /srv/app/htdocs/craft/app/framework/web/CWebApplication.php(282): CController->run('Subscribe')
#5 /srv/app/htdocs/craft/app/etc/web/WebApp.php(836): CWebApplication->runController('constantContact...')
#6 /srv/app/htdocs/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#7 /srv/app/htdocs/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#8 /srv/app/htdocs/craft/app/index.php(73): CApplication->run()
#9 /srv/app/htdocs/public/index.php(19): require_once('/srv/app/weat/h...')
#10 {main}`

**Comment by bobartlett** [comment]
Some files failed to upload and was causing my issue.
